### ISSUE TITLE
PaginationKey column does not exist

### ISSUE THREAD

**Issue by stmfcgcg** [benjamin658/typeorm-cursor-pagination#19]
I am having trouble reproducing this, I cannot reproduce the issue consistently but it is a show stopper for me.

If my pagination key is of a column that is not snake case, when the pagination criteria is added to the query it doesn't convert it to snake case

e.g.

// class definition 
```
@Entity
class MyClass {
   @Column({
       name: 'version_id'
   })
   versionId: string
}
```

// creation of paginator
```
buildPaginator({
  alias: 't',
  paginationKeys: ['versionId']
  query: {
    limit: 10,
    afterCursor: 'JHGHGFSSA' // after cursor has to be set to reproduce this
  },
  entity: MyClass
})
```

// resultant query:
`..... AND ("t"."versionId" < $1)) "distinctAlias"`
the above should be:
`..... AND ("t"."version_id" < $1)) "distinctAlias"`

notes:
Every field/column is correctlly converted to snake case, except for the pagination criteria defined above (including the select parameter which includes the column "version_id")

I believe the cause of the problem is the following code:

```
  private buildCursorQuery(where: WhereExpression, cursors: CursorParam, escape: EscapeFn): void {
    const operator = this.getOperator();
    const params: CursorParam = {};
    let query = '';
    this.paginationKeys.forEach((key) => {
      params[key] = cursors[key];
      where.orWhere(`${query}${escape(this.alias)}.${escape(key)} ${operator} :${key}`, params);
      query = `${query}${escape(this.alias)}.${escape(key)} = :${key} AND `;
    });
  }
```

`escape(key)` results in `connection.driver.escape` being invoked which in turn adds double quotes around versionId
I believe this is causing typeorm to not convert the column to snake case

It is hard to reproduce - last time I reproduced it I changed the limit from 200 to 10 and that caused the error. I am not clear as to why changing the limit would affect the generated query to expose this bug

Thx

Stu

**Comment by stmfcgcg** [comment]
@benjamin658 - I can confirm that removing escape(key) resolves my issue. Can you please create a new build?

regards

Stu

**Comment by benjamin658** [comment]
Hi @stmfcgcg , thanks for reporting the issue.

Did you try [typeorm-naming-strategies](https://www.npmjs.com/package/typeorm-naming-strategies) yet?

**Comment by stmfcgcg** [comment]
Hi Benjamin

I am using the SnakeNamingStrategy from the typeorm-naming-strategies, so every field is mapped correctly - except for the one used in the PaginationKeys. For some reason the double quotes caused by escape(key) causes typeorm to not map it correctly

Stu

**Comment by benjamin658** [comment]
Hi @stmfcgcg 

Please upgrade the version to v0.5.0, I have removed the escape function and use double quote instead.

Thanks

**Comment by stmfcgcg** [comment]
Won't it result in the same error? All the escape function did on postgress was add double quotes

**Comment by benjamin658** [comment]
Escape function or double quote are required by the `camel case` column.

**Comment by benjamin658** [comment]
@stmfcgcg Did you try pass the ["version_id"] as the paginationKeys?

**Comment by stmfcgcg** [comment]
version_id failed since you validate that versionId is a member of the object (versionId is, version_id is not) - there is also the type constraint on paginationKeys

aren't double quotes added after typeorm has mapped versionId to version_id?

At the point in code you add the where clause we are still in the application domain  i.e working with entities, properties of entities, etc. - before they have been mapped to their corresponding columns - hence the quotes are unnecessary since typeorm will add them once it has mapped the field in the object to the column in the database

if I write:
builder.andWhere('alias.versionId = .....')
There is no need to add the quotes around 'versionId'. As you have currently implemented it, the query will be:
builder.andWhere('"alias"."versionId" = ....')
Is this what you expect?

**Comment by benjamin658** [comment]
> version_id failed since you validate that versionId is a member of the object (versionId is, version_id is not) - there is also the type constraint on paginationKeys
> 
> aren't double quotes added after typeorm has mapped versionId to version_id?
> 
> At the point in code you add the where clause we are still in the application domain i.e working with entities, properties of entities, etc. - before they have been mapped to their corresponding columns - hence the quotes are unnecessary since typeorm will add them once it has mapped the field in the object to the column in the database
> 
> if I write:
> builder.andWhere('alias.versionId = .....')
> There is no need to add the quotes around 'versionId'. As you have currently implemented it, the query will be:
> builder.andWhere('"alias"."versionId" = ....')
> Is this what you expect?

I added double quote because of **Postgres folds identifiers to lowercase, unless you double-quote your identifiers.**
I will try to add more test cases of snake naming strategy and find the best way to support different naming strategy on every db type.

**Comment by stmfcgcg** [comment]
In the end I had to remove the escape on both the alias and the column name. If I did not remove the escape around the alias then typeorm did not resolve the column correctly and add the quotes properly. Below are the results of that query:

SELECT "m"."measurement_id" AS "m_measurement_id", "m"."value" AS "m_value", "m"."rating_id" AS "m_rating_id", "m"."issuer_id" AS "m_issuer_id", "m"."start_vendor_id" AS "m_start_vendor_id", "m"."end_vendor_id" AS "m_end_vendor_id", "m"."start_date" AS "m_start_date", "m"."end_date" AS "m_end_date" FROM "ethos_app"."measurement" "m" WHERE "m"."start_date" <= $1 and $2 <= "m"."end_date" AND ("m"."measurement_id" < $3) ORDER BY "m"."measurement_id" DESC LIMIT 10001 -- PARAMETERS: ["2020-11-30","2020-11-30","23d65727-7232-4212-9fed-8da457afe0f0"]

This is running against postgresql - as you can see, typeorm has added the correct quotes around the column names in the select and in the where criteria

**Comment by benjamin658** [comment]
Hi @stmfcgcg ,

After add some test cases of different naming strategy, I can confirm that you are right. #cc228793e33697d97b158d2a44c094a11951b09e #c2dcc64d49cd5f34e869418deaa39f6f55df9559

Simply remove the escape and double quote and let TypeORM handle the rest, it works perfect even on
PostgreSQL.

**Comment by benjamin658** [comment]
@stmfcgcg Please upgrade to v0.6.0.

Thanks.

**Comment by stmfcgcg** [comment]
Working perfectly - Thanks for resolving this

**Comment by benjamin658** [comment]
Thanks for your feedback!

**Comment by benjamin658** [comment]
Thank you for your feedback!
