### ISSUE TITLE
invalid input syntax for type timestamp

### ISSUE THREAD

**Issue by 0261** [benjamin658/typeorm-cursor-pagination#20]
Hi There. It's really useful when using cursor-based pagination. 
However, I can't use it for a while because of an error.

All "entities" in my project use date-related columns (for example, createdAt, updatedAt) declared as String type, not Date type.
If you hold the date type (updatedAt) with the pagination key and request a query, the typeorm gives an error message saying that it is an invalid input value.

The error message is as follows.
<img width="1140" alt="as" src="https://user-images.githubusercontent.com/25784935/107756530-adcec380-6d67-11eb-9cfb-4cc4b224d3b2.png">

Looking at the code you wrote, encodeURIComponent and decodeURIComponent were used when it was a String type. This seems to be because of this. Can you change this like a Number type?

**Comment by benjamin658** [comment]
Hi @0261 , could you share your code snippet?
In my test case, I use the Date type as a pagination key as well without any problem.
