### ISSUE TITLE
Make encode() method public

### ISSUE THREAD

**Issue by Cyberuben** [benjamin658/typeorm-cursor-pagination#25]
Hi,

our system uses several databases but we'd like to keep our responses consistent. We provide a cursor for each of the entities in our response. Could you make the `encode()` method public so that we don't have to manually wrap it ourselves?

It would be even better if we were able to provide our own `encode` or `decode` methods.

**Comment by benjamin658** [comment]
Hi @Cyberuben , thanks for your feedback.

In my opinion, `encode` method is an implementation details that should be encapsulated, so I think make the method public is not a good idea.

However, you still can fork the repo and do what you want.
