### ISSUE TITLE
Sort fields from relation table not working

### ISSUE THREAD

**Issue by darrylmabini** [benjamin658/typeorm-cursor-pagination#29]
Is it possible to sort fields from relations table. The Paginator alias can only use the [entity name.](https://github.com/benjamin658/typeorm-cursor-pagination/blob/master/src/Paginator.ts#L44) So if I have these entities and I used `EntityOne` as the Paginator entity - how can I sort the `hello_world` column from `EntityTwo`?

`EntityOne`
  - entity_one_id
  - foo_bar
  - entity_two_id
  - entityTwo -> joinColumn(entity_two_id)
  
`EntityTwo`
  - entity_two_id
  - hello_world

The `paginationKeys` option will only accepts `keyof` the used entity which is `EntityOne`

I tried `addOrderBy` but no luck.

Any suggestions is highly appreciated - thanks!

**Comment by benjamin658** [comment]
Related to #4
