### ISSUE TITLE
Entity props name error

### ISSUE THREAD

**Issue by walopper** [benjamin658/typeorm-cursor-pagination#3]
column in tables are changing to lowercase ignoring the entity model.

This will fix the issue

![image](https://user-images.githubusercontent.com/13891790/80011596-79b9a780-84a2-11ea-81ee-653882ceb4bd.png)

**Comment by benjamin658** [comment]
> column in tables are changing to lowercase ignoring the entity model.
> 
> This will fix the issue
> 
> ![image](https://user-images.githubusercontent.com/13891790/80011596-79b9a780-84a2-11ea-81ee-653882ceb4bd.png)

Thanks for opening the issue.

However, I don't understand what you mean about "column in tables are changing to lowercase ignoring the entity model.",  can you explain it in more detail? 

Thanks
