### ISSUE TITLE
Get SQL

### ISSUE THREAD

**Issue by renehauck** [benjamin658/typeorm-cursor-pagination#32]
Would it also be possible to just get the generated SQL query instead of executing it directly?
Background for this is that I would like to execute a pagination within a SubQuery.

Many thanks for this great tool.

**Comment by benjamin658** [comment]
Thanks for your feedback.

The library has to execute the query to build the cursor, so it could be useless if it only returns the SQL query. However, if you really need the pagination query, fork the repo and check:

https://github.com/benjamin658/typeorm-cursor-pagination/blob/b6a377ef42676ad6d49e519619cb560fa3441432/src/Paginator.ts#L76

Just simply return `this.appendPagingQuery(builder)` to get the query.
