### ISSUE TITLE
Modified query causes incorrect results

### ISSUE THREAD

**Issue by stuartf123** [benjamin658/typeorm-cursor-pagination#59]
Hi Benjamin, you have added the field paginationUniqueKey. This appears to result in missing rows when paging through a collection.

My class does not have a single column as a primary key, but the primary key is made from 3 columns. In this scenario, what should the value of this new field be?

**Comment by benjamin658** [comment]
How about just using `paginationKeys `?

**Comment by stuartf123** [comment]
I am not explicitly setting the value of the paginationUniqueKey. I believe you default the column name to be 'id' and so this results in your code still appending your additional criteria

Thx

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by benjamin658** [comment]
Would you mind providing the entity and sample data?

**Comment by benjamin658** [comment]
In the v0.10.0 release, paginationUniqueKey has been removed. Please upgrade and try again.
