### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by stmfcgcg** [benjamin658/typeorm-cursor-pagination#6]
Love the lilbrary. I have suggestion:

If there is a limit in the query and an inner join then typeorm executes multiple queries to the database. The 1st query is to retrieve the ids and the 2nd query to retrieve the values. The ids from the results of the first query are the parameters to the 2nd query. With a large number of results the performance is awful.

The above can be resolved by using a subquery:

    select id, col1, col2, col3 from outer o join (select id from outer o1 where ...... {paging parameters + limit}) o2 
    join .........
    where o.id = o2.id

    const queryBuilder = createQueryBuider(Outer, 'o').addFrom(query=>{
        return query.from('o1').select('id').where('..paging parameters....'
    )}, 'o2').where('o1.id = o2.id)

    const items = queryBuilder.getMany()

At the moment your framework only does the paging at the outer query but you have all the logic to be able to add the query parameters to the inner query and process the results to create the PagingResult.

An example using a modified version of your framework might be:

    const paginator = buildPaginator({
        entity: Outer,
        options: {limit: 100},
    });

    const queryBuilder = createQueryBuider(Outer, 'o').addFrom(query=>{
        return paginator.appendPagingQuery(query.from('o1').select('id').where('..paging parameters....'
    ))}, 'o2').where('o1.id =  o2.id)

    const items = paginator.getMany(queryBuilder);
    
What do you think?

**Comment by benjamin658** [comment]
Hi @stmfcgcg , thanks for your suggestion.

Actually I was wondering why the TypeORM executes `id IN (...)`  after the library append paging query to the query builder which lead to significant performance losses, and now you answered my question :)

I will spend some time fixing this issue to improve the performance.

**Comment by benjamin658** [comment]
Hi @stmfcgcg, I just release a beta version ff6e10d75488487fa015b823ae51fc99059de56f to solve the issue.

After a deep research, I found that the 2nd `id IN (...)` query is caused by `.take()` which is recommend by the [TypeORM document](https://typeorm.io/#/select-query-builder/using-pagination).

I try to use the `.innerJoin()` on sub query entity table with paging parameters and limit instead of using `.take()` on outer query.

Could you please update your package.json version to 
```
"typeorm-cursor-pagination": "0.3.0-beta.1"
```
and give it a try.

Please let me know if there are any problems, thanks!

**Comment by benjamin658** [comment]
Hi @stmfcgcg, I just released a beta version ff6e10d to solve the issue.

After a deep research, I found that the 2nd id IN (...) query is caused by .take() which is recommended by the TypeORM document.

I try to use the .innerJoin() on sub query entity table with paging parameters and limit instead of using .take() on outer query.

Could you please update your package.json version to
```
"typeorm-cursor-pagination": "0.3.0-beta.1"
```
and give it a try.

Please let me know if there are any problems, thanks!

**Comment by stmfcgcg** [comment]
Thanks Ben,

I will test it tonight

Stu

**Comment by stmfcgcg** [comment]
Sorry Ben – it didn’t work. It is related to the pagination keys. Here is my code to create the paginator

const paginator = buildPaginator({
    alias: 't',
    query: Object.assign({
        limit: Number.MAX_SAFE_INTEGER
    }, options),
    paginationKeys: ['versionId'],
    entity: Ticket
});

Notice that paginationKeys = [‘versionId]

Below is my class


 @Entity('ticket')
export class Ticket implements Auditable, Versionable {
    @Column('uuid')
    versionId: string;
...
}

I use the SnakeNamingStrategy from the npm package typeorm-naming-strategies

Below is the relevant part of the query that is generated:

SELECT "t"."version_id"                    AS "t_version_id",
FROM "ethos_app"."ticket" "t"
         INNER JOIN (SELECT versionId
                     FROM "ethos_app"."ticket" "paging"
                     ORDER BY "paging"."version_id" DESC
                     LIMIT 1001) "paging" ON "t"."version_id" = paging.versionId
ORDER BY "t"."version_id" DESC

The code generates ‘SELECT versionId’ – this should be ‘SELECT version_id’




From: Stuart Faircloth <stuart_faircloth@capgroup.com>
Date: Friday, July 3, 2020 at 10:45 AM
To: benjamin658/typeorm-cursor-pagination <reply@reply.github.com>
Subject: Re: [benjamin658/typeorm-cursor-pagination] Feature Request (#6)

Thanks Ben,

I will test it tonight

Stu

**Comment by stmfcgcg** [comment]
I think I have it working. I haven't given it a thorough testing yet. Changes to paginator.ts:

```
  private appendPagingQuery(builder: SelectQueryBuilder<Entity>): SelectQueryBuilder<Entity> {
    const cursors: CursorParam = {};

    if (this.hasAfterCursor()) {
      Object.assign(cursors, this.decode(this.afterCursor as string));
    } else if (this.hasBeforeCursor()) {
      Object.assign(cursors, this.decode(this.beforeCursor as string));
    }

    builder.innerJoin((paging) => {
      const pagingSubQuery = paging
        .from(this.entity, 'paging')
      this.paginationKeys.forEach(key=>
        pagingSubQuery.addSelect(`paging.${key}`, `paging_${key}`)
      )
      pagingSubQuery.limit(this.limit + 1)
        .orderBy(this.buildOrder('paging'));

      if (Object.keys(cursors).length > 0) {
        pagingSubQuery
          .andWhere(new Brackets((where) => this.buildCursorQuery(where, cursors)));
      }

      return pagingSubQuery;
    },
    'paging',
    this.buildPagingInnerJoinCondition());

    builder.orderBy(this.buildOrder(this.alias));

    return builder;
  }
```

```
  private buildPagingInnerJoinCondition(): string {
    return this.paginationKeys.reduce((prev, next) => {
      let query = `${this.alias}.${next} = "paging"."paging_${next}"`;
      if (prev !== '') {
        query = `AND ${query}`;
      }

      return `${prev} ${query}`;
    }, '');
  }
```

**Comment by stmfcgcg** [comment]
This approach is flawed - the inner query must include all the criteria which could filter the objects requested. Consider the following:
1. 500 entities
2. limit of 10
2 50 of the 500 meet the criteria but they aren't in the top 10 of the limit
3. The resultset will be empty

**Comment by benjamin658** [comment]
@stmfcgcg I have tried this approach before and suddenly realized that it doesn't work, just like you said the inner query builder must include all the outer builder's criteria. 

Thanks for your effort and feedback anyway. 👍
