### ISSUE TITLE
getEntityPropertyType returns incorrect value

### ISSUE THREAD

**Issue by drtyh2o** [benjamin658/typeorm-cursor-pagination#7]
I am getting the following error when using the paginator `version 0.2.2`:
```
Error: unknown type in cursor: [object]1593704679072
```
It appears that `getEntityPropertyType` is returning `object` as the property type rather than `number` for the `min_event_timestamp` property specified in `paginationKeys` 

Here is the entity:
```ts
TripEntity {
  recorded: 1593705279149,
  id: 1,
  trip_id: '42a4f404-b456-40c4-9b06-7f511eae6504',
  trip_status: 'completed',
  min_event_timestamp: 1593704679072,
  max_event_timestamp: 1593705279072
}
```
The following code returns `Object` when `key` is `min_event_timestamp`
```ts
Reflect.getOwnMetadata('design:type', this.entity.prototype, key).name
```

**Comment by benjamin658** [comment]
Hi @drtyh2o , can you provide the `TripEntity`  class?  

I will try to reproduce the error tomorrow,
