### ISSUE TITLE
invalid input syntax for type timestamp: \"Sat Jan 01 2000 00:59:53 GMT+0100 (West Africa Standard Time)\"

### ISSUE THREAD

**Issue by shellking4** [benjamin658/typeorm-cursor-pagination#78]
Hello. Thanks for the work on this package. I get this error when using createdAt as paginationKey. I guess it has to do with the format of the date but How can I solve it ?

**Comment by benjamin658** [comment]
It seems this error is returned by PostgreSQL; please check that the timestamp format is valid.

**Comment by shellking4** [comment]
> It seems this error is returned by PostgreSQL; please check that the timestamp format is valid.

Thank you for your reply. It's solved now. I'm going to close this issue by the way

**Comment by iamsr** [comment]
what's the solution for mysql? I have column like this -
 @CreateDateColumn() createdAt: string;
 
 the date format in pagination query for cursor is causing issue. I
