### ISSUE TITLE
Using camel-cased property names as pagination keys throws a QueryFailedError

### ISSUE THREAD

**Issue by eoin-obrien** [benjamin658/typeorm-cursor-pagination#8]
## Expected Behaviour

The user should be able to paginate an entity using a camel-cased property such as `createdAt`.

## Current Behavior

The call to `paginate` fails with the following error message:

     QueryFailedError: column "createdat" does not exist
      at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
      at Query.callback (src/driver/postgres/PostgresQueryRunner.ts:178:30)
      at Query.handleError (node_modules/pg/lib/query.js:145:17)
      at Connection.connectedErrorMessageHandler (node_modules/pg/lib/client.js:214:17)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:134:12)
      at addChunk (_stream_readable.js:286:12)
      at readableAddChunk (_stream_readable.js:268:9)
      at Socket.Readable.push (_stream_readable.js:209:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

## Steps to Reproduce

1. Create an entity with a camel-cased property. Note that the issue occurs regardless of the choice of column decorator; `@Column()`, `@CreateDateColumn()` and `@UpdateDateColumn()` can be used to produce identical errors.

```node
@Entity()
export class Post {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  title!: string;

  @Column()
  description!: string;

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;
}
```

2. Attempt to paginate the entity with at least one camel-cased property listed in `paginationKeys`.

```node
const paginator = buildPaginator({
    entity: Post,
    paginationKeys: ['createdAt', 'id']
});
const result = await paginator.paginate(queryBuilder);
```

3. Run the code and observe the error message specified above.

## Possible Solution

A potential solution for the issue would be to add double quotes to elements of the `paginationKeys` array in `Paginator.ts`.

I'm aiming to open a PR with a test case to reproduce the issue and a potential fix shortly. Thanks for creating this library, by the way, it's proved to be a great help on my lastest project!

**Comment by benjamin658** [comment]
Hi @eoin-obrien , that's a good catch, and thanks for your PR to solve the issue :)

**Comment by eoin-obrien** [comment]
You're most welcome, @benjamin658 — I'm glad I could be of service!

**Comment by chrismllr** [comment]
This may be off-topic, but has anyone seen this same issue for table names?

```
QueryFailedError: missing FROM-clause entry for table "usecase"
```

Where the rest of my query uses `useCase`. My gut feeling is something similar would be done for the `Paginator.getEntityPropertyType`, but still digging.

**Comment by benjamin658** [comment]
> This may be off-topic, but has anyone seen this same issue for table names?
> 
> ```
> QueryFailedError: missing FROM-clause entry for table "usecase"
> ```
> 
> Where the rest of my query uses `useCase`. My gut feeling is something similar would be done for the `Paginator.getEntityPropertyType`, but still digging.

Hi @chrismllr , Please try to upgrade to v0.6.0
